### ISSUE TITLE
open and click tracking not working with Mailgun

### ISSUE THREAD

**Issue by michaelzap** [mettle/sendportal#199] opened 2022-01-26 21:00 UTC
With the current stand-alone app using Mailgun as an email service, I am not seeing any opens or clicks reported in SendPortal reports. Open and click tracking is enabled in Mailgun, the tracking links are being substituted for regular links within the outgoing emails, and I do see opens and clicks in the Mailgun log. This data is not showing up inside SendPortal, however.

I haven't started digging yet, but does SendPortal use Mailgun's Events API?
https://documentation.mailgun.com/en/latest/api-events.html

**Comment by n0nag0n** [comment] 2022-04-19 17:36
I have an issue with this as well. Webhooks have been setup correctly, and the queue has been started and currently running with `php artisan queue:work --queue=sendportal-webhook-process`. I can see that webhooks are being processed with log messages like `Processing: Sendportal\Base\Listeners\Webhooks\HandleMailgunWebhook` but the counts never go up in sendportal

**Comment by n0nag0n** [comment] 2022-04-19 18:02
Actually through more digging, found out that mailgun webhooks aren't being signed correctly. 
```
local.ERROR: Mailgun webhook failed verification check.
```
When looking at the code here https://github.com/mettle/sendportal-core/blob/dfff6967fc4375fc896b280c3cc30ac8f1d6920d/src/Listeners/Webhooks/HandleMailgunWebhook.php#L184 it shows that it's trying to sign it with the api key that was supplied earlier.

This may be by design but I'm only going to be putting in a sending api key for mailgun, I will not put the global parent "private api key" in there. If you go to the API security page in Mailgun, there is a `HTTP webhook signing key` which should be used to compare the signatures of the webhook. 

For now, I'm just going to comment it out because the pull request to add a signing key to the email service form, saving it, then requiring it in the code is above my Laravel expertise. I don't think, but know I would break something :)

**Comment by shankhadevpadam** [comment] 2022-06-16 11:31
@n0nag0n I have also stuck with mailgun webhooks. @dljfield Can fix this issue?

**Comment by willselby** [comment] 2022-07-05 15:50
This should be resolved thanks to @shankhadevpadam's PR that was released with [v2.0.5](https://github.com/mettle/sendportal-core/releases/tag/v2.0.5).

**Closed by willselby** 2022-07-05 15:50 UTC
